{
 "title": "Database Collectd",
 "description": "CollectD & Graphite Server Metrics Dashboard with  CPU, Memory, IO & Disk Stats",
 "tags": [ "collectd" ],
 "time": { "from": "2020-06-27T09:03:15.853Z", "to": "2020-06-27T09:54:47.970Z" },
 "templating": {
  "list": [
   { "name": "prefix", "query": "collectd" },
   { "name": "server", "query": "$prefix.*" }
  ]
 },
 "panels": [
  {
   "title": "Max connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "$prefix.$server.postgresql.genki.gauge.pg_maxconnections"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias($prefix.$server.postgresql.genki.percent_bytes.pg_database_size, 'Database size')"
    }
   ]
  },
  {
   "title": "Current Connection Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByMetric($prefix.$server.postgresql.genki.gauge.pg_current_connection_count)"
    }
   ]
  },
  {
   "title": "Current Queue Jobs Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByMetric($prefix.$server.postgresql.genki.gauge.pg_current_job_count)"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "$prefix.$server.df.overlay.percent_bytes.used"
    }
   ]
  },
  {
   "title": "CPU Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(aliasByNode($prefix.$server.cpu.even-average.cpu.user, 3), 'user')"
    },
    {
     "target": "alias($prefix.$server.cpu.even-average.cpu.system, 'system')"
    }
   ]
  },
  {
   "title": "Read/Write IOPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(aliasByNode(perSecond($prefix.$server.disk.xvda.disk_ops.read), 3), 'Read IOPS')"
    },
    {
     "target": "alias(aliasByNode(perSecond($prefix.$server.disk.xvda.disk_ops.write), 3), 'Write IOPS')"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.memory.memory.{cached,free,buffered}, 4)"
    }
   ]
  },
  {
   "title": "Top 6 Largest Tables",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima($prefix.$server.postgresql.genki.pg_6_largest_table.*), 5)"
    }
   ]
  },
  {
   "title": "Num Deadlocks",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByMetric($prefix.$server.postgresql.genki.gauge.num_deadlocks)"
    }
   ]
  },
  {
   "title": "Top 10 ACTIVE tables",
   "type": "graph",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByMetric($prefix.$server.postgresql.genki.pg_10_table_active.*))"
    }
   ]
  },
  {
   "title": "Query Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByMetric($prefix.$server.postgresql.genki.pg_15_query_times_ms.*))"
    }
   ]
  },
  {
   "title": "Query Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByMetric($prefix.$server.postgresql.genki.pg_15_query_times_ms.*))"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.load.load.shortterm, 4)"
    }
   ]
  },
  {
   "title": "Network Packets/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(perSecond($prefix.$server.interface.*.if_packets.rx), 'in')"
    },
    {
     "target": "alias(perSecond($prefix.$server.interface.*.if_packets.tx), 'out')"
    }
   ]
  },
  {
   "title": "Process Fork/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond($prefix.$server.processes.fork_rate), 'new processes')"
    }
   ]
  },
  {
   "title": "Network Traffic/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(scale(perSecond($prefix.$server.interface.*.if_octets.rx), 8), 'in')"
    },
    {
     "target": "alias(scale(perSecond($prefix.$server.interface.*.if_octets.tx), 8), 'out')"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.processes.ps_state.*, 4)"
    }
   ]
  }
 ]
}